const songs = [
  {
    id: '1',
    name: 'Third Eye',
    band: 'TOOL',
    album: 'Aenima',
    year: 1996,
    length: '13:47',
  },
  {
    id: '2',
    name: 'Come as You Are',
    band: 'Nirvana',
    album: 'Nevermind',
    year: 1991,
    length: '3:39',
  },
  {
    id: '3',
    name: '7empest',
    band: 'TOOL',
    album: 'Fear Inoculum',
    year: 2019,
    length: '15:44',
  },
  {
    id: '4',
    name: 'Frizzle Fry',
    band: 'Primus',
    album: 'Frizzle Fry',
    year: 1990,
    length: '6:04',
  },
  {
    id: '5',
    name: 'Heart Shaped Box',
    band: 'Nirvana',
    album: 'In Utero',
    year: 1993,
    length: '4:41',
  },
  {
    id: '6',
    name: 'Pushit',
    band: 'TOOL',
    album: 'Aenima',
    year: 1996,
    length: '9:55',
  },
  {
    id: '7',
    name: 'Smells Like Teen Spirit',
    band: 'Nirvana',
    album: 'Nevermind',
    year: 1991,
    length: '5:01',
  },
  {
    id: '8',
    name: 'Here Come the Bastards',
    band: 'Primus',
    album: 'Sees of Cheese',
    year: 1991,
    length: '2:55',
  },
];
module.exports = { songs };
